export const DefaultAdminPermissions = [
	{
		moduleName: 'Users',
		sortId: 1,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Roles',
		sortId: 2,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Employment',
		sortId: 3,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Taxation',
		sortId: 3.1,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Salary',
		sortId: 4,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Payment Info',
		sortId: 5,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Documents',
		sortId: 7,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Earnings',
		sortId: 7.01,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Deductions',
		sortId: 7.02,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Time Shift',
		sortId: 7.1,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Time Logs',
		sortId: 7.2,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Time Activities',
		sortId: 7.3,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Time Sheets',
		sortId: 7.4,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Leave Request',
		sortId: 7.5,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Employee',
		sortId: 9,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Time Sheet',
		sortId: 10,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Payroll',
		sortId: 11,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Branch Code',
		sortId: 12,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Departments',
		sortId: 13,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Job Grade',
		sortId: 14,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Pay Point',
		sortId: 17,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Earning',
		sortId: 18,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Deduction',
		sortId: 19,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Cost Center',
		sortId: 19.1,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Category Code',
		sortId: 19.2,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Job Title',
		sortId: 19.3,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},

	{
		moduleName: 'Leave Management',
		sortId: 19.4,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Holidays',
		sortId: 19.5,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: false,
	},
	{
		moduleName: 'Payroll Reports',
		sortId: 20,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Earning and Deduction Reports',
		sortId: 21,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Tax Reports',
		sortId: 22,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Loan Request',
		sortId: 23,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Mid-Month Pay',
		sortId: 24,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Attendance Report',
		sortId: 26,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Company Setup',
		sortId: 27,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Statutory Components',
		sortId: 27.1,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Pay Schedule',
		sortId: 28,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Earnings Code',
		sortId: 29,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Deduction Code',
		sortId: 30,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Mid-Month Pay Setup',
		sortId: 31,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
	{
		moduleName: 'Payroll History',
		sortId: 32,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
		approval: true,
	},
];

export const DefaultPermissions = [
	{
		moduleName: 'Users',
		sortId: 1,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Roles',
		sortId: 2,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Employment',
		sortId: 3,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Taxation',
		sortId: 3.1,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Salary',
		sortId: 4,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Payment Info',
		sortId: 5,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Documents',
		sortId: 7,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Earnings',
		sortId: 7.01,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Deductions',
		sortId: 7.02,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Time Shift',
		sortId: 7.1,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Time Logs',
		sortId: 7.2,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Time Activities',
		sortId: 7.3,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Time Sheets',
		sortId: 7.4,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Leave Request',
		sortId: 7.5,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Employee',
		sortId: 9,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Time Sheet',
		sortId: 10,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Payroll',
		sortId: 11,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Branch Code',
		sortId: 12,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Departments',
		sortId: 13,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Job Grade',
		sortId: 14,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Pay Point',
		sortId: 17,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Earning',
		sortId: 18,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Deduction',
		sortId: 19,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Cost Center',
		sortId: 19.1,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Category Code',
		sortId: 19.2,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Job Title',
		sortId: 19.3,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Leave Management',
		sortId: 19.4,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Holidays',
		sortId: 19.5,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Payroll Reports',
		sortId: 20,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Earning and Deduction Reports',
		sortId: 21,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Tax Reports',
		sortId: 22,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Loan Request',
		sortId: 23,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Mid-Month Pay',
		sortId: 24,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Attendance Report',
		sortId: 26,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Company Setup',
		sortId: 27,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Statutory Components',
		sortId: 27.1,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Pay Schedule',
		sortId: 28,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Earnings Code',
		sortId: 29,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Deduction Code',
		sortId: 30,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Mid-Month Pay Setup',
		sortId: 31,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
	{
		moduleName: 'Payroll History',
		sortId: 32,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
		approval: false,
	},
];

export const roles = [
	{
		name: 'Admin',
		description: 'All company permissions granted',
		isAdmin: true,
	},
	{
		name: 'Image Manager',
		description: 'All modules except organization settings',
		isAdmin: false,
	},
	{
		name: 'Salt Composition Manager',
		description: 'Employee Engagement only',
		isAdmin: false,
	},
];

export const defaultCompanies = [
	{
		name: 'Test Company',
		address: '905',
		email: 'pp757439@gmail.com',
	}
];